name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t danikohale/yii2 . -f dockerfile

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB }}" | docker login -u danikohale2002@gmail.com --password-stdin

    - name: Push image
      run: docker push danikohale/yii2:latest
    - name: docker up
      run: docker compose up
